spring:
  application:
    name: education-spring-boot

  devtools:
    restart:
      enabled: true

  docker:
    compose:
      enabled: true

  datasource:
    url: jdbc:postgresql://db.shigdmqucvwofhgnbhyb.supabase.co:5432/postgres
    username: postgres
    password: 8QMzd9Zcqk*d8mt
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 5000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

cloudinary:
  cloud-name: dtxsewajc
  api-key: 679738922476866
  api-secret: ZI7OomWDo57P2ivu_kiBAAO7-s8

logging:
  level:
    root: INFO
    com.example: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        core:
          env: DEBUG
